const express = require('express');
const router = express.Router();
const { protect, authorize } = require('../middleware/authMiddleware');
const { applyCoupon,removeCoupon,getCoupons,createCoupon,updateCoupon,deleteCoupon } = require('../controllers/mainController');
router.post('/apply', protect, applyCoupon);
router.post('/remove', protect, removeCoupon);
router.get('/', protect, authorize('admin'), getCoupons);
router.post('/', protect, authorize('admin'), createCoupon);
router.put('/:id', protect, authorize('admin'), updateCoupon);
router.delete('/:id', protect, authorize('admin'), deleteCoupon);
module.exports = router;
