const express = require('express');
const router = express.Router();
const { protect } = require('../middleware/authMiddleware');
const { createOrder,getUserOrders,getOrderById,cancelOrder } = require('../controllers/mainController');
const { orderValidator } = require('../middleware/validationMiddleware');
router.post('/', protect, orderValidator, createOrder);
router.get('/', protect, getUserOrders);
router.get('/:id', protect, getOrderById);
router.put('/:id/cancel', protect, cancelOrder);
module.exports = router;
